/******************************************************************************
**  TITLE:         OUTPUTMSX.C
**  DESCRIPTION:   I/O routines for the binary output file used by the
**                 EPANET Multi-Species Extension toolkit.
**  AUTHORS:       L. Rossman, US EPA - NRMRL
**                 F. Shang, University of Cincinnati
**                 J. Uber, University of Cincinnati
**  VERSION:       1.00
**  LAST UPDATE:   10/5/06
******************************************************************************/

#include <stdio.h>
#include <string.h>
#include <math.h>
#include "typesmsx.h"
#define  EXTERN_MSX extern
#include "globals.h"

//  Local variables
//-----------------
static long  ResultsOffset;            // Offset byte where results begin
static long  NodeBytesPerPeriod;       // Bytes per time period used by all nodes
static long  LinkBytesPerPeriod;       // Bytes per time period used by all links

//  Imported functions
//--------------------
double quality_getNodeQual(int j, int m);
double quality_getLinkQual(int k, int m);

//  Exported functions
//--------------------
int   output_open(void);
int   output_saveInitialResults(void);
int   output_saveResults(void);
int   output_saveFinalResults(void);
float output_getNodeQual(int k, int j, int m);
float output_getLinkQual(int k, int j, int m);


//=============================================================================

int output_open()
/*
**  Purpose:
**    opens an MSX binary output file.
**
**  Input:
**    none.
**
**  Returns:
**    an error code (or 0 if no error).
*/
{
// --- close output file if already opened

    if (OutFile.file != NULL) fclose(OutFile.file);

// --- try to open the file

    if ( (OutFile.file = fopen(OutFile.name, "w+b")) == NULL)
    {
        return ERR_OPEN_OUT_FILE;
    }

// --- write initial results to file

    Nperiods = 0;
    output_saveInitialResults();
    return 0;
}

//=============================================================================

int output_saveInitialResults()
/*
**  Purpose:
**    saves general information to beginning of MSX binary output file.
**
**  Input:
**    none.
**
**  Returns:
**    an error code (or 0 if no error).
*/
{
    int  m, n;
    INT4 magic = MAGICNUMBER;
    INT4 version = VERSION;

    rewind(OutFile.file);
    fwrite(&magic, sizeof(INT4), 1, OutFile.file);              //Magic number
    fwrite(&version, sizeof(INT4), 1, OutFile.file);            //Version number
    fwrite(&Nobjects[NODE], sizeof(INT4), 1, OutFile.file);     //Number of nodes
    fwrite(&Nobjects[LINK], sizeof(INT4), 1, OutFile.file);     //Number of links
    fwrite(&Nobjects[SPECIE], sizeof(INT4), 1, OutFile.file);   //Number of species
    fwrite(&Rstep, sizeof(INT4), 1, OutFile.file);              //Reporting step size
    for (m=1; m<=Nobjects[SPECIE]; m++)
    {
        n = strlen(Specie[m].id);
        fwrite(&n, sizeof(INT4), 1, OutFile.file);              //Length of specie ID
        fwrite(Specie[m].id, sizeof(char), n, OutFile.file);    //Specie ID string
    }
    for (m=1; m<=Nobjects[SPECIE]; m++)
    {
        fwrite(&Specie[m].units, sizeof(INT4), 1, OutFile.file);  //Specie units string
    }
    ResultsOffset = ftell(OutFile.file);
    NodeBytesPerPeriod = Nobjects[NODE]*Nobjects[SPECIE]*sizeof(float);
    LinkBytesPerPeriod = Nobjects[LINK]*Nobjects[SPECIE]*sizeof(float);
    return 0;
}


//=============================================================================

int output_saveResults()
/*
**  Purpose:
**    saves computed species concentrations for each node and link at the
**    current time period to the MSX binary output file.
**
**  Input:
**    none.
**
**  Returns:
**    an error code (or 0 if no error).
*/
{
    int   m, j;
    float x;

    for (m=1; m<=Nobjects[SPECIE]; m++)
    {
        for (j=1; j<=Nobjects[NODE]; j++)
        {
            x = (float)quality_getNodeQual(j, m);
            fwrite(&x, sizeof(float), 1, OutFile.file);
        }
    }

    for (m=1; m<=Nobjects[SPECIE]; m++)
    {
        for (j=1; j<=Nobjects[LINK]; j++)
        {
            x = (float)quality_getLinkQual(j, m);
            fwrite(&x, sizeof(float), 1, OutFile.file);
        }
    }
    return 0;
}

//=============================================================================

int output_saveFinalResults()
/*
**  Purpose:
**    saves the following information to the end of the MSX binary output file:
**    - byte offset into file where WQ results for each time period begins,
**    - total number of time periods written to the file,
**    - any error code generated by the analysis (0 if there were no errors),
**    - the Magic Number to indicate that the file is complete.
**
**  Input:
**    none.
**
**  Returns:
**    an error code (or 0 if no error).
*/
{
    INT4 magic = MAGICNUMBER;

    fwrite(&ResultsOffset, sizeof(INT4), 1, OutFile.file);
    fwrite(&Nperiods, sizeof(INT4), 1, OutFile.file);
    fwrite(&ErrCode, sizeof(INT4), 1, OutFile.file);
    fwrite(&magic, sizeof(INT4), 1, OutFile.file);
    return 0;
}

//=============================================================================

float output_getNodeQual(int k, int j, int m)
/*
**  Purpose:
**    retrieves a result for a specific node from the MSX binary output file.
**
**  Input:
**    k = time period index
**    j = node index
**    m = specie index.
**
**  Returns:
**    the requested specie concentration.
*/
{
    float c;
    long bp = ResultsOffset + k * (NodeBytesPerPeriod + LinkBytesPerPeriod);
    bp += ((m-1)*Nobjects[NODE] + (j-1)) * sizeof(float);
    fseek(OutFile.file, bp, SEEK_SET);
    fread(&c, sizeof(float), 1, OutFile.file);
    return c;
}

//=============================================================================

float output_getLinkQual(int k, int j, int m)
/*
**  Purpose:
**    retrieves a result for a specific link from the MSX binary output file.
**
**  Input:
**    k = time period index
**    j = link index
**    m = specie index.
**
**  Returns:
**    the requested specie concentration.
*/
{
    float c;
    long bp = ResultsOffset + ((k+1)*NodeBytesPerPeriod) + (k*LinkBytesPerPeriod);
    bp += ((m-1)*Nobjects[LINK] + (j-1)) * sizeof(float);
    fseek(OutFile.file, bp, SEEK_SET);
    fread(&c, sizeof(float), 1, OutFile.file);
    return c;
}
