/******************************************************************************
**  TITLE:         OUTPUTMSX.C
**  DESCRIPTION:   I/O routines for the binary output file used by the
**                 EPANET Multi-Species Extension toolkit.
**  AUTHORS:       L. Rossman, US EPA - NRMRL
**                 F. Shang, University of Cincinnati
**                 J. Uber, University of Cincinnati
**  VERSION:       1.00
**  LAST UPDATE:   10/5/06
******************************************************************************/

#include <stdio.h>
#include <string.h>
#include <math.h>
#include "typesmsx.h"
#define  EXTERN_MSX extern
#include "globals.h"

//  Local variables
//-----------------
static long  ResultsOffset;            // Offset byte where results begin
static long  NodeBytesPerPeriod;       // Bytes per time period used by all nodes
static long  LinkBytesPerPeriod;       // Bytes per time period used by all links

//  Imported functions
//--------------------
double quality_getNodeQual(int j, int m);
double quality_getLinkQual(int k, int m);

//  Exported functions
//--------------------
int   output_open(void);
int   output_saveInitialResults(void);
int   output_saveResults(void);
int   output_saveFinalResults(void);
float output_getNodeQual(int k, int j, int m);
float output_getLinkQual(int k, int j, int m);


//=============================================================================

int output_open()
/*
**  Purpose:
**    opens an MSX binary output file.
**
**  Input:
**    none.
**
**  Returns:
**    an error code (or 0 if no error).
*/
{
// --- close output file if already opened

    if (MSXOutFile.file != NULL) fclose(MSXOutFile.file);

// --- try to open the file

    if ( (MSXOutFile.file = fopen(MSXOutFile.name, "w+b")) == NULL)
    {
        return ERR_OPEN_OUT_FILE;
    }

// --- write initial results to file

    MSXNperiods = 0;
    output_saveInitialResults();
    return 0;
}

//=============================================================================

int output_saveInitialResults()
/*
**  Purpose:
**    saves general information to beginning of MSX binary output file.
**
**  Input:
**    none.
**
**  Returns:
**    an error code (or 0 if no error).
*/
{
    int  m, n;
    INT4 magic = MAGICNUMBER;
    INT4 version = VERSION;

    rewind(MSXOutFile.file);
    fwrite(&magic, sizeof(INT4), 1, MSXOutFile.file);              //Magic number
    fwrite(&version, sizeof(INT4), 1, MSXOutFile.file);            //Version number
    fwrite(&MSXNobjects[NODE], sizeof(INT4), 1, MSXOutFile.file);     //Number of nodes
    fwrite(&MSXNobjects[LINK], sizeof(INT4), 1, MSXOutFile.file);     //Number of links
    fwrite(&MSXNobjects[SPECIE], sizeof(INT4), 1, MSXOutFile.file);   //Number of species
    fwrite(&MSXRstep, sizeof(INT4), 1, MSXOutFile.file);              //Reporting step size
    for (m=1; m<=MSXNobjects[SPECIE]; m++)
    {
        n = strlen(MSXSpecie[m].id);
        fwrite(&n, sizeof(INT4), 1, MSXOutFile.file);              //Length of specie ID
        fwrite(MSXSpecie[m].id, sizeof(char), n, MSXOutFile.file);    //MSXSpecie ID string
    }
    for (m=1; m<=MSXNobjects[SPECIE]; m++)
    {
        fwrite(&MSXSpecie[m].units, sizeof(INT4), 1, MSXOutFile.file);  //MSXSpecie units string
    }
    ResultsOffset = ftell(MSXOutFile.file);
    NodeBytesPerPeriod = MSXNobjects[NODE]*MSXNobjects[SPECIE]*sizeof(float);
    LinkBytesPerPeriod = MSXNobjects[LINK]*MSXNobjects[SPECIE]*sizeof(float);
    return 0;
}


//=============================================================================

int output_saveResults()
/*
**  Purpose:
**    saves computed species concentrations for each node and link at the
**    current time period to the MSX binary output file.
**
**  Input:
**    none.
**
**  Returns:
**    an error code (or 0 if no error).
*/
{
    int   m, j;
    float x;

    for (m=1; m<=MSXNobjects[SPECIE]; m++)
    {
        for (j=1; j<=MSXNobjects[NODE]; j++)
        {
            x = (float)quality_getNodeQual(j, m);
            fwrite(&x, sizeof(float), 1, MSXOutFile.file);
        }
    }

    for (m=1; m<=MSXNobjects[SPECIE]; m++)
    {
        for (j=1; j<=MSXNobjects[LINK]; j++)
        {
            x = (float)quality_getLinkQual(j, m);
            fwrite(&x, sizeof(float), 1, MSXOutFile.file);
        }
    }
    return 0;
}

//=============================================================================

int output_saveFinalResults()
/*
**  Purpose:
**    saves the following information to the end of the MSX binary output file:
**    - byte offset into file where WQ results for each time period begins,
**    - total number of time periods written to the file,
**    - any error code generated by the analysis (0 if there were no errors),
**    - the Magic Number to indicate that the file is complete.
**
**  Input:
**    none.
**
**  Returns:
**    an error code (or 0 if no error).
*/
{
    INT4 magic = MAGICNUMBER;

    fwrite(&ResultsOffset, sizeof(INT4), 1, MSXOutFile.file);
    fwrite(&MSXNperiods, sizeof(INT4), 1, MSXOutFile.file);
    fwrite(&MSXErrCode, sizeof(INT4), 1, MSXOutFile.file);
    fwrite(&magic, sizeof(INT4), 1, MSXOutFile.file);
    return 0;
}

//=============================================================================

float output_getNodeQual(int k, int j, int m)
/*
**  Purpose:
**    retrieves a result for a specific node from the MSX binary output file.
**
**  Input:
**    k = time period index
**    j = node index
**    m = specie index.
**
**  Returns:
**    the requested specie concentration.
*/
{
    float c;
    long bp = ResultsOffset + k * (NodeBytesPerPeriod + LinkBytesPerPeriod);
    bp += ((m-1)*MSXNobjects[NODE] + (j-1)) * sizeof(float);
    fseek(MSXOutFile.file, bp, SEEK_SET);
    fread(&c, sizeof(float), 1, MSXOutFile.file);
    return c;
}

//=============================================================================

float output_getLinkQual(int k, int j, int m)
/*
**  Purpose:
**    retrieves a result for a specific link from the MSX binary output file.
**
**  Input:
**    k = time period index
**    j = link index
**    m = specie index.
**
**  Returns:
**    the requested specie concentration.
*/
{
    float c;
    long bp = ResultsOffset + ((k+1)*NodeBytesPerPeriod) + (k*LinkBytesPerPeriod);
    bp += ((m-1)*MSXNobjects[LINK] + (j-1)) * sizeof(float);
    fseek(MSXOutFile.file, bp, SEEK_SET);
    fread(&c, sizeof(float), 1, MSXOutFile.file);
    return c;
}
